### ISSUE TITLE
Is it ok to use `ArcSwap` in async environment?

### ISSUE THREAD

**Issue by cjwcommuny** [vorner/arc-swap#118]
For example, would it causes deadlock in the async environment?

**Comment by vorner** [comment]
ArcSwap is lock-free. There is no way to cause a deadlock with it.

However, if you hold too many Guards to the same arc-swap, you may get a slight slow-down (we are talking about micro-optimization speeds here, and async switching of tasks will be probably an order of magnitude slower than this slow-down).

https://docs.rs/arc-swap/latest/arc_swap/docs/performance/index.html
