### ISSUE TITLE
Wrong link in crate root docs

### ISSUE THREAD

**Issue by whentze** [vorner/arc-swap#15]
This line: https://github.com/vorner/arc-swap/blob/16154775ca2223612084564901441ce042504d35/src/lib.rs#L15 refers to `IndependentArcSwap` but links to `ArcSwapOption`.

**Comment by vorner** [comment]
Thank you. I've fixed in master, but I think it is small enough not to release a new version just because of this. It'll ride with the next release.

**Comment by whentze** [comment]
:+1:
