### ISSUE TITLE
Support Null?

### ISSUE THREAD

**Issue by vorner** [vorner/arc-swap#5]
It could sometimes be desirable to represent empty state. eg. some form of NULL. On the other hand, every user would then need to explicitly handle the NULL case even if it doesn't happen for them. Is it worth?

**Comment by Diggsey** [comment]
You could make it generic, ie. `Swap<T: RefCounted>` and have `ArcSwap` be an alias, and also implement `RefCounted` for `Option<Arc<T>>`

**Comment by vorner** [comment]
That's actually a nice idea. And it could be also implemented (under a feature) for all these `Arc`s from other crates without weak counts, etc.

**Comment by vorner** [comment]
Implemented and released as part of 0.2
